### ISSUE TITLE
Missing MDF files in the project

### ISSUE THREAD

**Issue by ericvelasco-dev** [xCONFLiCTiONx/Social-Post-Scheduler#1]
Would you mind guiding us with the issue of the missing .mdf files

Could not copy the file "C:\xxxxx\xxxx\Downloads\Social-Post-Scheduler-master\SocialPostScheduler\SocialPostScheduler.mdf" because it was not found.

![image](https://user-images.githubusercontent.com/43733736/103748122-9997f800-503e-11eb-8c8b-f44a9482f3f1.png)

**Comment by xCONFLiCTiONx** [comment]
The intended way is to use the bacpac file in /Prerequisites/Import Database/ to create the database using SQL Server Management Studio but the easiest would be to use the one in the release. The problem with the latter is that if I'm updating the program to more functionality and have to upgrade the database too then that release may not suffice so if you're serious and want to do it right then go with SSMS.

Also, the latter option is using MSLocalDB2019 so you'll likely have to recreate the instance to the updated version if you strictly installed everything through Visual Studio.

**Comment by ericvelasco-dev** [comment]
I saw the .bacpac file, let me check maybe that could fix the issue. Thanks a lot.
